// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEsjD9EEWZHzS1qY1F98yIasCU7Qsgz6s',
    appId: '1:275536287139:web:d4a753823e86c36ce0f616',
    messagingSenderId: '275536287139',
    projectId: 'tictactoe-98857',
    authDomain: 'tictactoe-98857.firebaseapp.com',
    databaseURL: 'https://tictactoe-98857-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tictactoe-98857.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYbG9s8kVpMIGEgjYVRwgoud7AdjJ2Kw',
    appId: '1:275536287139:android:f466c0149b8b0a52e0f616',
    messagingSenderId: '275536287139',
    projectId: 'tictactoe-98857',
    databaseURL: 'https://tictactoe-98857-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tictactoe-98857.appspot.com',
  );
}
